### PR TITLE
[de] some german translations Update

### PR DESCRIPTION
**Pull request by sotten**
some german translations
Update de.json

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@sotten, we have changed the structure of the project.

`json/de.json` has been moved to a new location: `locales/de/de.json`.

**Comment by andrey-helldar** [comment]
```bash
git fetch --all
git checkout -b "patch/d58d7a0" "d58d7a08d64e78a4a3d2f7bfa9eefd58831b19ed"
git switch master
git rebase patch/d58d7a0 master
git push
```

**Comment by sotten** [comment]
> ```shell
> git fetch --all
> git checkout -b "patch/d58d7a0" "d58d7a08d64e78a4a3d2f7bfa9eefd58831b19ed"
> git switch master
> git rebase patch/d58d7a0 master
> git push
> ```

an error occurs when performing step two.
I am not experienced enough with Git to solve the problem myself. I can create a new pull request based on a current fork. Is this ok?
I like the changes in version 9.

**Comment by andrey-helldar** [comment]
@sotten, one of the simplest ways is to copy your files to another folder, download the latest version of the code from the repository, move the files to the replacement folder, commit and push.

**Comment by sotten** [comment]
da347eb3a6b85efdd9994e16f2d7c5a9ae73f0d0

**Comment by sotten** [comment]
#1622

**Pull request closed without merging**
