### PR TITLE
Added full spanish translations to 'es.json' for Laravel Jetstream

### PR DESCRIPTION
**Pull request by luisprmat**
until v1.2.1

### CODE REVIEW

**Comment by caouecs** [comment]
Gracias but... in your translations, we don't have same tags than #1335 

@andrey-helldar

**Comment by andrey-helldar** [comment]
I can check the keys later.

**Comment by luisprmat** [comment]
of course, I have added the new tags supported up to version 1.2.1 of the stubs for livewire and others that will be supported in the next jetstream release

**Comment by luisprmat** [comment]
Fixed conflict only for `es.json`. It only remains to add the new tags to the other `.json`

**Comment by andrey-helldar** [comment]
Код выглядит грязным. Непонятно что Вы добавили.

**Comment by andrey-helldar** [comment]
The code looks messy.  It is not clear what you added.

**Comment by andrey-helldar** [comment]
@caouecs, everything seems to be good.

**Comment by luisprmat** [comment]
@andrey-helldar The added tags are in alphabetical order like the other files, just check jetstream and you will see that it is missing a lot. However feel free to delete my PR

**Comment by andrey-helldar** [comment]
@luisprmat, Sorry, the previous message was written from the phone, I evaluated the code incorrectly.

**Pull request closed without merging**
