### PR TITLE
patch 5 az

### PR DESCRIPTION
**Pull request by hs-qwerty**
patch 5

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Can you resolve conflict?

**Comment by andrey-helldar** [comment]
Will there be more translations or is that all?

**Comment by hs-qwerty** [comment]
I want to translate the all az.json file

**Comment by andrey-helldar** [comment]
Let's do this. I am now accepting the changes and releasing a version.

When you translate the rest of the keys, I can also release a new version 😊

**Review by andrey-helldar — APPROVED** [review]
Thank you

**Pull request merged**
