### PR TITLE
[IT] Added italian translation for Owner role of Jetstream

### PR DESCRIPTION
**Pull request by rinodrummer**
I've seen that there's no translation for Owner role in Jetstream.

### CODE REVIEW

**Comment by masterix21** [comment]
Grazie @rinodrummer 

PR approved (@andrey-helldar @caouecs)

**Review by andrey-helldar — COMMENTED** [review]
The [source/packages/jetstream.json](https://github.com/Laravel-Lang/lang/blob/master/source/packages/jetstream.json) file does not contain the `Owner` key.

You do not need to add it manually.

When will the key be added?

When the Laravel team publishes a Jetstream release, [our script](https://github.com/Laravel-Lang/lang/blob/master/app/main/Processors/Packages.php) will automatically find all the keys used in the translation in it and add them to all localizations.

What happens if we just accept this PR: the script will see that there is no `Owner` key in the Jetstream project and will simply remove it from all files.

**Comment by caouecs** [comment]
So, I close ?

**Comment by andrey-helldar** [comment]
@caouecs, Yes. There is no point in accepting it. The script will delete the extra keys anyway.

**Comment by andrey-helldar** [comment]
@caouecs, wait, don't close.

Have a question for the author: @rinodrummer, do you add the key for the Jetstream project yourself or was it our script did not find it in the project? Can you show where it is used?

**Comment by rinodrummer** [comment]
I added it in `jetstream.json` by my own not thinking that it is auto-generate, I tried to search about the file but haven't found any information about it, so I thought that it has to be added there manually since I found even "Administrator" and "Editor", which are the other two default roles.

By the way, the `OwnerRole`'s name has no translations, so I added it to `it.json` too.

**Comment by andrey-helldar** [comment]
@rinodrummer, understood. Unfortunately, the script automatically scans the Jetstream project files and updates the keys. If the file contains keys that are not in the Jetstream project, the script will delete them.

**Pull request closed without merging**
