### PR TITLE
[gu] New language

### PR DESCRIPTION
**Pull request by GeneralCheesecake**

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you, but can you translate validation-inline.php and json file please ?

**Comment by andrey-helldar** [comment]
@GeneralCheesecake, can you translate **`validation-inline.php`** and **`{locale}.json`** file please ?

**Comment by caouecs** [comment]
@Laravel-Lang/laravel-lang we publish, we close ?

**Comment by andrey-helldar** [comment]
@caouecs, I have no complaints about the current translation files. Plus they are clean.

I propose to accept these changes. And when @GeneralCheesecake returns, it will be able to translate other files as well.

**Comment by luisprmat** [comment]
I think that we must merge. Hopefully someone will translate the missing files later.

**Pull request merged**
