### PR TITLE
Added template preset like laravel/framework

### PR DESCRIPTION
**Pull request by andrey-helldar**
See https://github.com/laravel/framework/tree/master/.github and https://github.com/laravel/framework/issues/new/choose

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you

**Comment by andrey-helldar** [comment]
😊

image

image

**Comment by caouecs** [comment]
The same for Pull Request with mandatory informations : languages, files

**Comment by andrey-helldar** [comment]
At first I wanted to create a file for PR, but I couldn't think of what text to insert into it :(

**Pull request merged**
