### PR TITLE
Update korean translation string

### PR DESCRIPTION
**Pull request by Hoto-Cocoa**
Updated some incorrect/weird translations.

Note: "to" can be "에", "으로", "위해", and etc...
"I'm going to home" -> "집에/으로(to) 가고 있습니다"
"I bought new Laptop to join Online conference" -> "온라인 회의에 참석하기 위해(to) 새 노트북을 구매했습니다"

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you, but can you add missing translations in json file ? https://github.com/Laravel-Lang/lang/blob/master/todo.md#ko

**Comment by Hoto-Cocoa** [comment]
OK, I will translate. But It may take some time because of my job.

**Comment by Hoto-Cocoa** [comment]
Added translation of missing strings.

**Comment by caouecs** [comment]
Thank you, I sort the tags ;)

**Pull request merged**
