### PR TITLE
[tr] fix: Machine translation of missing keys, other fixes.

### PR DESCRIPTION
**Pull request by mertasan**
Please close the #1661

I have corrected all the translations.

### CODE REVIEW

**Comment by caouecs** [comment]
thank you

**Comment by caouecs** [comment]
For countries, I add its in exclude files ? It's same in Turkish than in English ? https://laravel-lang.github.io/lang/statuses/tr.html

**Comment by mertasan** [comment]
@caouecs As far as I can see, nothing is missing. Country names are also in Turkish.

**Comment by caouecs** [comment]
Ok, I add countries in exclude file

**Comment by mertasan** [comment]
@caouecs I hope I didn't get it wrong. Country names are not the same as in English. It was translated into Turkish.

**Comment by caouecs** [comment]
oups, sorry, I fix

**Comment by caouecs** [comment]
In fact , some countries were not translated, like Hong Kong or Honduras

**Comment by caouecs** [comment]
it's not a problem, you can translate its, and you or I can delete tags in exclude file ;)

thank you for your help

**Comment by mertasan** [comment]
@caouecs Actually, there are some exceptions. They are not all different. Some are the same.

screenshot 125
screenshot 126


**English**:**Turkish**
Afghanistan: Afganistan
Albania: Arnavutluk
Algeria: Cezayir
Argentina: Arjantin
Australia: Avustralya
Austria: Avusturya
Azerbaijan: Azerbaycan
Belgium: Belçika
Brazil: Brazilya
Bulgaria: Bulgaristan
Canada: Kanada
China: Çin
Cyprus: Kıbrıs
Czechia: Çekya
Denmark: Danimarka
Egypt: Mısır
England: İngiltere
Finland: Finlandiya
France: Fransa
Georgia: Gürcistan
Germany: Almanya
Greece: Yunanistan
Holland / Netherlands: Hollanda
Hungary: Macaristan
India: Hindistan
Iran: İran
Iraq: Irak
Italy: İtalya
Israel: İsrail
Japan: Japonya
Jordan: Ürdün
Latvia: Letonya
Libya: Libya
Mexico: Meksika
Morocco: Fas
Pakistan: Pakistan
Poland: Polonya
Portugal: Portekiz
Romania: Romanya
Russia: Rusya
Saudi Arabia: Suudi Arabistan
Scotland: İskoçya
South Korea: Güney Kore
Spain: İspanya
Sweden: İsveç
Switzerland: İsviçre
Syria: Suriye
Thailand: Tayland
Turkey: Türkiye
Ukraine: Ukrayna
United Kingdom / UK: Birleşik Krallık
United States / USA: Amerika Birleşik Devletleri / ABD

**Comment by mertasan** [comment]
@caouecs https://translate.google.com.tr/?sl=tr&tl=en&text=Honduras%0AHong%20Kong%0A%C4%B0ngiltere%0AAlmanya%0AParis&op=translate

**Comment by caouecs** [comment]
yes, I wanted to say if there is not update to do, it's ok, it's in exclude file, but if the tag needs a translation, you can do it and I will delete it from the exclude file

I think we are agree together

**Comment by mertasan** [comment]
okey I just got it. :) thanks for everything.

**Pull request merged**
