### PR TITLE
[th]: Fix translations related to resources

### PR DESCRIPTION
**Pull request by bact**
- Fix mistranslated (machine translated?) strings related to "resource"
- Some other minor fixes

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
ขอบคุณ

**Comment by andrey-helldar** [comment]
@bact, Hi!

I noticed that you have [resigned](https://github.com/orgs/Laravel-Lang/people) from the Laravel Lang Team. Should I leave a link to your profile on our [documentation](https://laravel-lang.com/our-team.html) page or should it be removed?

Or did you not accept the invitation to join the team? @caouecs [sent it](https://github.com/Laravel-Lang/lang/pull/4164#issuecomment-1892746361) on January 15th.

**Comment by bact** [comment]
Ah.. I thought I would be automatically added - -"
How to accept?

**Comment by andrey-helldar** [comment]
@bact, when a new team member is adding, GitHub sends a invite link to email, where it's up to the person to decide whether or not to accept it. This link has an expiration date.

@caouecs, can you resend the invite?

**Comment by bact** [comment]
I see. Thank you @andrey-helldar and @caouecs . I will put my eyes on my inbox this time.

**Pull request merged**
