### PR TITLE
[nl] Update validation.php

### PR DESCRIPTION
**Pull request by devfrey**
* Removed the 'Het' + 'veld' combinations, because it will never result in grammatically correct translations (see https://github.com/Laravel-Lang/lang/pull/2083#discussion_r834622158).
* Replaced literal translations with more common/natural translations.
* Avoided compound nouns ([samenstellingen](https://onzetaal.nl/taaladvies/samenstelling)).

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]

**Comment by andrey-helldar** [comment]
@WhereIsLucas, can you check?

**Comment by andrey-helldar** [comment]
@devfrey, can you check which of the translations fits the context better?

A merge conflict occurred after merging a #2087.

**Comment by devfrey** [comment]
@andrey-helldar I've rebased against `main` 👍

**Review by andrey-helldar — APPROVED** [review]
@WhereIsLucas, can you check this PR?

**Comment by andrey-helldar** [comment]
Dankjewel

**Pull request merged**
