### PR TITLE
update fa.json

### PR DESCRIPTION
**Pull request by Kamandlou**

### CODE REVIEW

**Comment by Kamandlou** [comment]
update fa.json

**Comment by caouecs** [comment]
thank you

**Comment by caouecs** [comment]
@Kamandlou Can you help us to translate other tags ? We did an automatic translation in https://github.com/Laravel-Lang/lang/pull/1681 Thanks by advance

**Comment by Kamandlou** [comment]
> @Kamandlou Can you help us to translate other tags ? We did an automatic translation in #1681 Thanks by advance

Yes, I have been involved in my project for some time, after the project I will definitely translate the rest of the tags

**Pull request merged**
