### PR TITLE
Migrated files from Publisher project

### PR DESCRIPTION
**Pull request by andrey-helldar**
I see two possible options for releasing these changes:

1. Minor version (for example, `10.2`). In this case, I will release patch `10.3.1` for the [`publisher`](https://github.com/Laravel-Lang/publisher), in which I will prohibit the use of lang version `10.2` and higher.

2. Major version (for example, `11.0`). In this case, I will release a patch for the [`publisher`](https://github.com/Laravel-Lang/publisher) indicating the minimum allowed version of the `laravel-lang/lang`.

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@caouecs, 

The changes are ready.

I took the classes out of the publisher, so I put them where they should be.

**Comment by caouecs** [comment]
I look at the code this week end

**Comment by caouecs** [comment]
For me, we don't touch to the translation files, so it's a minor version ( sorry for the lag )

**Comment by andrey-helldar** [comment]
No problem)

**Comment by andrey-helldar** [comment]
@caouecs, I propose to merge after January 10th.

Since the changes in this repository are minor, then at release this will break the [`publisher`](https://github.com/Laravel-Lang/publisher), since it now contains the same files to implement compatibility.

And I won't be able to make corrections until January 10th if my https://github.com/Laravel-Lang/publisher/pull/197 doesn't work.

**Comment by caouecs** [comment]
ok

**Comment by andrey-helldar** [comment]
@caouecs, I'm ready 😎

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
