### PR TITLE
[PL] All complete

### PR DESCRIPTION
**Pull request by olsza**

### CODE REVIEW

**Review by luisprmat — COMMENTED** [review]
Respect to `es.json` the proposed changes already are merged in the branch `master`.
I don't undestand why a [PL] translation needs to do changes in 8 files!!

**Review by luisprmat — CHANGES_REQUESTED** [review]
I suggest in this case to @olsza send a PR only modifying `pl.json` to avoid unexpected conflicts!

**Comment by caouecs** [comment]
@olsza Thank you, but can you do a pull request with just pl.json ?

**Comment by olsza** [comment]
I think I'm doing a pull request, but if not what am I doing wrong?
I do not hide that this is my first project, where I participate in Open Source, maybe someone will send a link where it will be more explained step by step how to do it, I will be VERY grateful

**Review by andrey-helldar — COMMENTED** [review]
There was a bug in your PR - it includes other commits.
Fetch the latest changes to your repository, create a branch inheriting from "master", commit the changes and submit a clean PR from your branch to the "master".

**Pull request closed without merging**
