### PR TITLE
Updated translation

### PR DESCRIPTION
**Pull request by arm092**

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you, can you help us with the json file ?

**Comment by arm092** [comment]
> Thank you, can you help us with the json file ?

May be

**Comment by arm092** [comment]
> Thank you, can you help us with the json file ?

Can you give me access to push?

**Comment by andrey-helldar** [comment]
> > Thank you, can you help us with the json file ?
> 
> Can you give me access to push?

It's not obligatory. Just create a commit on the same branch and push. The commit will automatically fall into this PR.

**Comment by arm092** [comment]
> > > Thank you, can you help us with the json file ?
> > 
> > 
> > Can you give me access to push?
> 
> It's not obligatory. Just create a commit on the same branch and push. The commit will automatically fall into this PR.
> 
> Or create a new one PR.

I cloned the repo, created a new branch arm092/armenian, edited files, and committed, but can't push the branch now. It shows the permission problem

**Comment by caouecs** [comment]
you do a pull request, not a push, like this PR

**Pull request merged**
