### PR TITLE
[ms] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@kamaroolkarim can you help us and review this automatic pull request, please ? thanks by advance

**Comment by caouecs** [comment]
I merge this machine translation, but it's possible to do a pull request after to fix words, see [contributing section](https://github.com/Laravel-Lang/lang/blob/master/docs/contributing-to-dev.md)

**Comment by kamaroolkarim** [comment]
hi @caouecs . sorry for my late response. i missed the notification. i've reviewed the machine translation and make some amendment on the translation. you can review it here #1720 https://github.com/Laravel-Lang/lang/pull/1720

**Comment by caouecs** [comment]
No problem, thank you for your help

**Pull request merged**
