### PR TITLE
Updated passwords.php

### PR DESCRIPTION
**Pull request by unknownbreakdown**
Translations have been slightly modified in order to follow the same formal pattern of translations in other files.

### CODE REVIEW

**Review by luisprmat — APPROVED** [review]
These changes are consistent, but in this issue, it is good to clarify that in Spanish there are two ways of expressing oneself in relation to the pronoun ***you*** (second person).
The first one uses **usted** and is [more formal](https://www.maidertomasena.com/como-decidir-si-escribir-de-tu-o-de-usted-en-la-web-de-tu-negocio/), the second uses the pronoun ***tú*** and it is [more friendly](https://es.wikipedia.org/wiki/Tuteo) and generates more confidence and is also quite used.
In this project we are using the first way in most translations (with these corrections I hope in all).
But I agree to consider the possibility of opening a second *set* of translations for Spanish where we only use the second way ***tú***, @caouecs I don't know if this is possible and what would be the best way to do it.

**Comment by caouecs** [comment]
Of course, it's possible to have es-usted and es-tu versions

but it's a double work ;)

**Comment by luisprmat** [comment]
There is also no problem in merging this PR

**Comment by caouecs** [comment]
Gracias

**Pull request merged**
