### PR TITLE
[km] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@seakmengc  can you help us and review this automatic pull request, please ? thanks by advance

**Comment by seakmengc** [comment]
> @seakmengc can you help us and review this automatic pull request, please ? thanks by advance

Sure, I'm reviewing it now. 😄

**Comment by seakmengc** [comment]
@andrey-helldar Could you please check `Allow edits from maintainers` so that I can push the update?

**Comment by caouecs** [comment]
I can merge this pull request, and you will be able to do a pull request directly here

**Comment by andrey-helldar** [comment]
> @andrey-helldar Could you please check `Allow edits from maintainers` so that I can push the update?

Ready

image

**Pull request merged**
