### PR TITLE
[nl]: Add missing translations in json

### PR DESCRIPTION
**Pull request by astalpaert**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@WhereIsLucas, can you check this PR?

**Comment by nunhes** [comment]
lang update

**Review by andrey-helldar — APPROVED** [review]
Dankjewel

**Comment by astalpaert** [comment]
> Dankjewel

You're welcome! Do you guys participate Hacktoberfest?

**Comment by andrey-helldar** [comment]
@astalpaer, me not

**Pull request merged**
