### PR TITLE
update fa translation

### PR DESCRIPTION
**Pull request by ariaieboy**
i wish with this PR the FA language Status become green

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
Thank you

**Comment by andrey-helldar** [comment]
@ariaieboy, do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by ariaieboy** [comment]
@andrey-helldar No problem, I'm happy to work on this project

**Comment by caouecs** [comment]
Welcome :)

**Pull request merged**
