### PR TITLE
[ro] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@vodnicearv can you help us and review this automatic pull request, please ? thanks by advance

**Comment by vodnicearv** [comment]
yes, of course

**Review by vodnicearv — CHANGES_REQUESTED** [review]
some edits need to be made, but I can do them later

**Comment by vodnicearv** [comment]
@andrey-helldar you used deepl to translate?

**Comment by caouecs** [comment]
> @andrey-helldar you used deepl to translate?

Yandex

**Comment by vodnicearv** [comment]
deepl has recently added many new languages

higher quality than all the other machine translation systems

**Comment by vodnicearv** [comment]
@caouecs maybe connect crowdin.com to make work with translations easier? for open-source projects it is free

**Comment by caouecs** [comment]
> @caouecs maybe connect crowdin.com to make work with translations easier? for open-source projects it is free

deepl is too expensive, but for crowdin.com, why not... just to see if it's possible to export in php files

**Comment by vodnicearv** [comment]
yes deepl is expensive :)
crowdin work perfectly with php and with laravel translations, and has a great integration with github repository

**Comment by vodnicearv** [comment]
wrote to deepl support to ask if they would be willing to give a free API key for an opensource project

**Comment by andrey-helldar** [comment]
@vodnicearv, as I wrote in the [discussion](https://github.com/Laravel-Lang/lang/discussions/1692), I couldn't use Google Translate as they charge $40 per hour to access their API. The Yandex.Translate service completed the translation of all phrases in about 1.5 hours and charged $5.28.

**Comment by caouecs** [comment]
> some edits need to be made, but I can do them later

@vodnicearv   I merge and you do a pull request after ?

**Comment by vodnicearv** [comment]
@caouecs ok

**Comment by caouecs** [comment]
done

**Pull request merged**
