### PR TITLE
[ar] Translate the new key

### PR DESCRIPTION
**Pull request by mohamedsabil83**
Phrase: **This coupon code can only be used by new customers**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
شكرا،

**Comment by mohamedsabil83** [comment]
العفو 😎

**Comment by andrey-helldar** [comment]
Pardons?

**Comment by andrey-helldar** [comment]
Aaaa)))) Looks like Google doesn't know this word :)

image

**Comment by mohamedsabil83** [comment]
Same word, multi-meaning. but the nearest one for **Pardon** is **عذرا** which also can mean **Sorry**, **Excuse me**, etc

**Comment by andrey-helldar** [comment]
Understood thanks)

**Comment by mohamedsabil83** [comment]
You're welcome

**Pull request merged**
