### PR TITLE
Fixed/#1377

### PR DESCRIPTION
**Pull request by olsza**
please CR @andrey-helldar :)

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]

**Comment by andrey-helldar** [comment]
PR includes changes from # 1395

**Review by andrey-helldar — CHANGES_REQUESTED** [review]
Remove code related to another PR (#1395)

**Review by andrey-helldar — APPROVED** [review]
The #1395 was accepted. I think there will be no conflict when uniting.
But, for the future, do not combine different code from different PRs in one.

**Comment by andrey-helldar** [comment]
@caouecs, allow to merge 😊

**Comment by olsza** [comment]
> The #1395 was accepted. I think there will be no conflict when uniting.
> But, for the future, do not combine different code from different PRs in one.

it was a separate branch, ie the translations were on 'master' and I sent "Pull, then I made a new branch and sent this branch here to RC. Later I go to Github and see that GitHub itself put them together: /
(probably because he was telling me that he could see a commit called fided #xxx)

thx @andrey-helldar

**Comment by caouecs** [comment]
I will merge this evening ( French time ) I want to check the code before ;)

**Comment by luisprmat** [comment]
@olsza maybe you must do a rebase of remote upstream in your master branch first before of send a new Push with your commits

**Comment by olsza** [comment]
ok, what do you think, should I leave this branch as it is, or do it from scratch, as @luisprmat suggested?
I will definitely do what @luisprmat wrote in the future;)

ps. thanks all :)

**Comment by andrey-helldar** [comment]
> ok, what do you think, should I leave this branch as it is, or do it from scratch, as @luisprmat suggested?
> I will definitely do what @luisprmat wrote in the future;)
> 
> ps. thanks all :)

The PR containing some of these commits is already merged into master, so there will be no conflict, BUT I suggest making this PR clean.

I see two options:
1. On your computer, you roll back the branch changes, clear the code and send force-push to the same branch. So the changes will go to this PR.
2. Create a new PR with a clean branch.

Correct me if I'm wrong, but I think you are new to git, so the second option seems easier to me.

**Comment by olsza** [comment]
I'm not new to Git at all, but I've used it for my projects, but the fact I'm new to GitHub and the open-source project.
I also agree that option 2 is better and faster in my opinion ;)

**Pull request closed without merging**
