### PR TITLE
`:trialDays` is a numberic value hence it displays {:trialDays} in the view instead of `30` or smth 

### PR DESCRIPTION
**Pull request by makowskid**
`:trialDays` is a numberic value hence it displays {:trialDays} in the view instead of `30` or smth 

might be the same case for `:days` vs `:Days` and `:amount` vs `:Amount`, I'm not sure

### CODE REVIEW

**Comment by andrey-helldar** [comment]
When looking for options to translate, all sentences start with a capital letter so that it is grammatically correct. But, as you noticed, this doesn't work with numbers.

I'll check the mechanics of working with locales again and, if I can't come up with a workaround, I'll remove the variable conversion at the beginning of the string.

At this time, let the PR be open, because if you accept it, the script will revert everything back, and we don't need that.

**Comment by andrey-helldar** [comment]
Strangely, I couldn't find the problem....

Json files:

```
// lang/en.json
{
  ":trialDays Day Trial": ":TrialDays aaaa"
}

// lang/sv.json
{
    ":trialDays Day Trial": ":TrialDays bbbb"
}
```
Calls and outputs:
```php
dd(
    __(':trialDays Day Trial', ['trialDays' => 'foo'], 'en'),
    __(':trialDays Day Trial', ['trialDays' => 'foo'], 'sv'),
);

"Foo aaaa" // routes\console.php:6
"Foo bbbb" // routes\console.php:6
```
```php
dd(
    __(':trialDays Day Trial', ['trialDays' => '30'], 'en'),
    __(':trialDays Day Trial', ['trialDays' => '30'], 'sv'),
);

"30 aaaa" // routes\console.php:6
"30 bbbb" // routes\console.php:6
```
```php
dd(
    __(':trialDays Day Trial', ['trialDays' => 30], 'en'),
    __(':trialDays Day Trial', ['trialDays' => 30], 'sv'),
);

"30 aaaa" // routes\console.php:6
"30 bbbb" // routes\console.php:6
```
And a non-standard key transfer:
```php
dd(
    __(':trialDays Day Trial', ['TrialDays' => 30], 'en'),
    __(':trialDays Day Trial', ['TrialDays' => 30], 'sv'),
);

"30 aaaa" // routes\console.php:6
"30 bbbb" // routes\console.php:6
```

Can you give me the exact code that leads to this problem so I can check?

**Comment by makowskid** [comment]
Latest Laravel version.
I'm using Laravel Spark and this placeholder is not replaced properly unless changed to lowercase.

**Comment by andrey-helldar** [comment]
Are you using the open source [Laravel Spark Aurelius](https://github.com/laravel/spark-aurelius) or the paid version of [Laravel Spark](https://spark.laravel.com)?

In the free version, I found code like this:

https://github.com/laravel/spark-aurelius/blob/9db0edc5fe1d067305797a46e9e45f116890d476/resources/views/auth/register-common.blade.php#L109-L111

My steps:

1. Updated `composer.json` file like this:
    ```json
    {
        "repositories": [
            {
                "type": "github",
                "url": "git@github.com:laravel/spark-aurelius.git"
            }
        ]
    }
    ````
2. Call the `composer require laravel/spark-aurelius` console command.
3. Update localizations via `php artisan lang:update` console command (Swedish locale are installed).
4. Create a new blade file with content:
    ```html
    <table>
        <tr>
            <td>English</td>
            <td>
                <?php echo __(':trialDays Day Trial', ['trialDays' => '{{ plan.trialDays }}'], 'en'); ?>
            </td>
        </tr>
        <tr>
            <td>Swedish</td>
            <td>
                <?php echo __(':trialDays Day Trial', ['trialDays' => '{{ plan.trialDays }}'], 'sv'); ?>
            </td>
        </tr>
    </table>
    ```
5. Create a new route:
    ```php
    app('router')->get('some', fn () => view('some'));
    ```
6. And I'm looking at the results:

    image

Can you check how this is implemented with [Spark Stripe](https://spark.laravel.com)?

**Comment by makowskid** [comment]
it uses `Base.js` mixin
```
export default {
    methods: {
        __(key, replace) {
            var translation = window.translations[key] ? window.translations[key] : key;

            _.forEach(replace, (value, key) => {
                translation = translation.replace(':'+key, value);
            });

            return translation;
        },
    },
}
```

**Comment by andrey-helldar** [comment]
Understood. This is a flaw in the JS function, since in PHP it looks like this:

https://github.com/laravel/framework/blob/082345d76fc6a55b649572efe10b11b03e279d24/src/Illuminate/Translation/Translator.php#L246-L254

It turns out that until changes are made to Spark, the method will not work correctly.

I have [released](https://github.com/Laravel-Lang/status-generator/releases/tag/2.1.0) an updated version of the `Status Generator` which will now not convert the beginning of a sentence.

**Review by andrey-helldar — APPROVED** [review]

**Comment by andrey-helldar** [comment]
I released version [13.4.0](https://github.com/Laravel-Lang/lang/releases/tag/13.4.0) and also sent an email to the Laravel team suggesting improvements to this script.

Thanks 🤝

**Comment by andrey-helldar** [comment]
@makowskid, hi!

It is likely that the script in Spark will be improved in the near future.

<details><summary>Reply from Dries Vints</summary>

image

</details>

**Comment by andrey-helldar** [comment]
@makowskid, more good news:

> This should be fixed now in v4.2.9
>
> Dries Vints

**Pull request merged**
