### PR TITLE
[lt] Update untranslated validation rules

### PR DESCRIPTION
**Pull request by ekateiva**
Added some missing 🇱🇹 Lithuanian validation translation.

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
It's ok for me

**Comment by masterix21** [comment]
Sorry but this is not the Italian language. I can't help you @andrey-helldar

**Comment by andrey-helldar** [comment]
@masterix21, oh sorry. I read "lt" as "it", not as "LT" 😅

**Comment by andrey-helldar** [comment]
@ekateiva, thank you!

**Comment by masterix21** [comment]
@andrey-helldar, you need a holiday 🤣

**Pull request merged**
