### PR TITLE
[11.x] Upgrade to new structure

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, guys!

Don't translate anything in the project yet. I am updating the structure. Made it more flexible and powerful.

For example, now we can translate fields such as:

```json
"password": "Le mot de passe est incorrect",
"password.letters": "The :attribute must contain at least one letter.",
"password.mixed": "The :attribute must contain at least one uppercase and one lowercase letter.",
"password.numbers": "The :attribute must contain at least one number.",
"password.symbols": "The :attribute must contain at least one symbol.",
"password.uncompromised": "The given :attribute has appeared in a data leak. Please choose a different :attribute.",
```

For old and new Laravel versions 🙂

It remains for me to refactor the connection of files to the framework for the publisher. This is about one hour of work.

Tomorrow morning I plan to release a new structure 🦾

**Comment by luisprmat** [comment]
👍, It's perfect. I have been waiting this moment. Also for fixing docs of lang/attributes system

**Comment by andrey-helldar** [comment]
@luisprmat, new structure available in attributes, http-statuses and skeleton templates:

- https://github.com/Laravel-Lang/translations-template
- https://github.com/Laravel-Lang/http-statuses
- https://github.com/Laravel-Lang/attributes

Soon I will release an update for the lang project.

**Comment by arman-arif** [comment]
I had updated some translations in the locales/bn/bn.json file. Should I create a PR now or wait for the release?

**Comment by andrey-helldar** [comment]
@arman-arif, create PR. I will restart the key upgrade script.

**Comment by arman-arif** [comment]
> @arman-arif, create PR. I will restart the key upgrade script.

Done.

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, version 11 has been [released](https://github.com/Laravel-Lang/lang/releases/tag/11.0.0).

The main changes are described in the [release note](https://github.com/Laravel-Lang/lang/releases/tag/11.0.0).

**Comment by andrey-helldar** [comment]
@ariaieboy, yes, I'll fix it now. Thank you.

**Pull request merged**
