### PR TITLE
[uk]: Updated uk translation 100%

### PR DESCRIPTION
**Pull request by Oleksandr-Moik**
Contains several changes that are separated by commits for all keys)

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
Дуже дякую!

**Comment by andrey-helldar** [comment]
Do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by Oleksandr-Moik** [comment]
I am interested in your offer. Yes! 

I would be happy to join your team and support new translations. Thanks

**Comment by andrey-helldar** [comment]
@caouecs, can you add a new member in team?

@Oleksandr-Moik, you indicate only in Ukrainian or Russian, too?

**Comment by Oleksandr-Moik** [comment]
> @Oleksandr-Moik, you indicate only in Ukrainian or Russian, too?

No, just Ukrainian. It's more convenient for me on it.

**Comment by andrey-helldar** [comment]
@Oleksandr-Moik, ok. No problem. I already added it to the [referents](https://laravel-lang.com/referents.html) table (the [plugin](https://github.com/TheDragonCode/vite-plugin-github-linkify) for processing links is still in development), and Fred, will add it to the team a little later, as soon as it is available.

**Comment by caouecs** [comment]
done

Welcome !

**Comment by Oleksandr-Moik** [comment]
It's a pleasure. Thanks!

**Pull request merged**
