### PR TITLE
Change name of Turkey to new official name Türkiye

### PR DESCRIPTION
**Pull request by lwohlhart**
The countries name change to Türkiye was accepted and confirmed by the UN on 26 May 2022 https://www.un.org/en/about-us/member-states/turkiye

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Try writing this word in English without a Turkish keyboard layout.

Also, the files in the `source` folder do not need to be changed manually. They are automatically updated from parent projects.

**Comment by andrey-helldar** [comment]
@slvler, what do you think?

**Comment by lwohlhart** [comment]
Hi, I was unsure about whether or not to change the occurence in `_excludes.json`. I was guessing that this array targets the `key` "Turkey" and not the value. Thank you fixing that

**Comment by lwohlhart** [comment]
Should I add a revert-commit for the changes in the `source`  directory?

**Comment by andrey-helldar** [comment]
@lwohlhart, so, look: we can easily change the values in all localizations except English, because once a day the script automatically checks all Laravel projects, downloads translation files from them and replaces them in the `source` folder. At the same time, English localization files are also automatically replaced by this script. To make changes to the English localization, you need to propose changes to all projects where the country name is used:

- https://github.com/laravel/spark-aurelius-mollie/blob/v2/install-stubs/resources/lang/en.json#L575
- https://github.com/laravel/spark-aurelius/blob/12.x/install-stubs/resources/lang/en.json#L563
- https://nova.laravel.com

**Comment by andrey-helldar** [comment]
> Should I add a revert-commit for the changes in the `source` directory?

Yes

**Comment by lwohlhart** [comment]
Regarding "Try writing this word in English without a Turkish keyboard layout":  I'm not entirely sure if it's okay to spell it as "Turkiye".

Sure if it's a real blocker for you for accepting the MR - let's do it like this; but I guess the name change was particularly targeting this spelling.

Let me know if it's a must 😉

**Comment by andrey-helldar** [comment]
Above in the post, I thought about this thought and [`proposed`](https://github.com/Laravel-Lang/lang/pull/2545#issuecomment-1364143383) a solution.

Your changes are in place and will be reviewed by @slvler. So I agree to changes.

**Comment by lwohlhart** [comment]
K sry, I get it now.
Sure I'll give it a go and try to propose changes in the other projects as well.
Thanks for your immediate reactions and feedbacks ;-)

**Comment by lwohlhart** [comment]
Concerning Nova:
Since I didn't find a better way to do it I started a discussion there
https://github.com/laravel/nova-issues/discussions/5182

**Comment by andrey-helldar** [comment]
@lwohlhart, the Laravel team has nothing to do with our project, but they can make changes to their code 👍

**Comment by andrey-helldar** [comment]
@slvler, that do you say?

**Review by andrey-helldar — APPROVED** [review]
I think we can accept this PR as the proposed changes have been officially confirmed at the government level.

Teşekkür Ederim

**Comment by lwohlhart** [comment]
👌 Thank you for the delightful collaboration

**Pull request merged**
