### PR TITLE
[es] Translate new tags for Laravel Jetstream 2FA confirmation

### PR DESCRIPTION
**Pull request by luisprmat**
New tags for Laravel Jetstream!!

@Laravel-Lang/laravel-lang

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Gracias

**Comment by mohamedsabil83** [comment]
Thanks

**Comment by mohamedsabil83** [comment]
@andrey-helldar just did 😄

**Comment by andrey-helldar** [comment]
@mohamedsabil83, yes, I got a notification 😀

**Comment by andrey-helldar** [comment]
[10.4.12](https://github.com/Laravel-Lang/lang/releases/tag/10.4.12) relased 🙂

**Pull request merged**
