### PR TITLE
[pt_BR]: Missing translations

### PR DESCRIPTION
**Pull request by pinsard**
Added missing translations, to achieve 100% completion status.

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@EuCarlos hi! Can you check this PR?

**Review by andrey-helldar — APPROVED** [review]
I think we can accept that now and adjust as necessary.

Obrigado!

**Review by EuCarlos — COMMENTED** [review]
I regret the delay in responding, but I am pleased to confirm that all translations have been thoroughly reviewed and are accurate.

**Comment by andrey-helldar** [comment]
@EuCarlos, obrigado!

**Pull request merged**
