### PR TITLE
[en, es] Add translation of new tags for Jetstream permissions

### PR DESCRIPTION
**Pull request by luisprmat**

### CODE REVIEW

**Comment by luisprmat** [comment]
We had forgotten this important translation.
* [Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn't receive the email, we will gladly send you another.](https://github.com/laravel/jetstream/blob/1.x/stubs/resources/views/auth/verify-email.blade.php#L8)

**Comment by caouecs** [comment]
Gracias

**Comment by luisprmat** [comment]
Pending update `todo.md`

**Comment by caouecs** [comment]
done

**Pull request merged**
