### PR TITLE
[ar] Add translations for spark and new password rules

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you

**Comment by mohamedsabil83** [comment]
You're welcome

**Comment by zak965** [comment]
A lot of files and translations missing. Specially global.php

**Comment by mohamedsabil83** [comment]
> A lot of files and translations missing. Specially global.php

All locales got keys from the **en** source. If there are missing keys, You can make a **PR** to update the **en** source.
The Github action will auto-push those keys to all locales. Then, we will translate it.

**Comment by zak965** [comment]
[en.zip](https://github.com/Laravel-Lang/lang/files/6395905/en.zip)
Here is all the files for latest version of Laravel

**Comment by mohamedsabil83** [comment]
> [en.zip](https://github.com/Laravel-Lang/lang/files/6395905/en.zip)
> Here is all the files for latest version of Laravel

Can you provide a source URL for those keys and from which package?

**Comment by zak965** [comment]
https://laraclassified.bedigit.com/

**Comment by zak965** [comment]
I can provide full translation of 10 languages from source website. I can zip and upload them here.

**Comment by mohamedsabil83** [comment]
This package for core packages from Laravel only

**Pull request merged**
