### PR TITLE
[zh_*] Update translations.

### PR DESCRIPTION
**Pull request by overtrue**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
谢谢你

**Comment by andrey-helldar** [comment]
@overtrue, can you translate the missing keys?

- [zh_CN](https://laravel-lang.com/statuses/zh-cn.html) - 4 missed
- [zh_HK](https://laravel-lang.com/statuses/zh-hk.html) - 8 missed
- [zh_TW](https://laravel-lang.com/statuses/zh-tw.html) - 9 missed

**Comment by overtrue** [comment]
No problem, I will do it later.

**Comment by andrey-helldar** [comment]
Thank you 🙂

**Pull request merged**
