### PR TITLE
[ar] Translate a few missing translations

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
شكراً لك

**Comment by mohamedsabil83** [comment]
العفو
btw, the meaning of **You're welcome** in Russia?

**Comment by andrey-helldar** [comment]
@mohamedsabil83, in Russian, the phrase "you're welcome" is perceived depending on the context and may have different variants. For exaple:

- I am glad to help
- Contact more
- You're welcome
- No problem
- Ready for everything for you

For example, in the context of a dialog, it would look like this:

- Give me a chair, please.
- Here, take it.
- Thanks.
- You are welcome.

**Comment by andrey-helldar** [comment]
That is, this phrase expresses some kind of gratitude in response to the word "thank you."

**Comment by mohamedsabil83** [comment]
my bad, I mean the translation of **You're welcome**? like in Arabic, when someone says **شكرا** the other reply **العفو**. what are the equivalents in Russian?

**Comment by andrey-helldar** [comment]
There is also another difference between Russian and English.

For example, in English the word "please" is used in the context of asking for help. For example, "give me a chair, please."

In Russian, the word "please" has many meanings and also depends on the context. For example:

- Give me a chair, please.
- Take
- Thanks
- Please

In the first request, the word "please" has the meaning of a polite request, and at the end of the dialogue, its meaning is gratitude for something.

In Russian, such a dialogue will be completely correctly constructed, but in English it has an incorrect construction.

In English, there is a clearer division of context between "please" and "you're welcome".

**Comment by andrey-helldar** [comment]
| English | Arabic | Common Russian | Colloquial Russian |
|---|---|---|---|
| Thank you | شكرا | Спасибо | Благодарю |
| You're welcome | العفو | Пожалуйста | Всегда пожалуйста. Всё для тебя. Рад помочь. Рад быть полезным |

**Comment by mohamedsabil83** [comment]
like **عفوا** in Arabic, it can handle much meaning according to the situation and how the speaker says it:
- Thank you. **You're welcome**.
- **Please**, can you give me a chair?
- pronounce it with stress to let the other person know you don't agree with what he says 😆

**Comment by andrey-helldar** [comment]
Yes exactly. In Russian, the meanings of words are understood from the context and the stress is always the same.

Even if someone changes the accents as a joke, the meaning will not be changed.

**Comment by andrey-helldar** [comment]
You can also add emotional coloring.

For example,

- Дай мне стул, пожалуйста. Give me a chair, please.
- Возьми. Take.
- Спасибо. Thanks.
- Пожалуйста. You are welcome

(nice dialogue)

- Дай мне стул, пожалуйста. Give me a chair, please.
- Возьми. Take.
- Ну спасибо. Oh, thanks
- Да пожалуйста. Yes please

(haughty tone)

🙂

**Pull request merged**
