### PR TITLE
[ja] update translation

### PR DESCRIPTION
**Pull request by wadakatu**
Added some translation in ja.json.

Hope it helps.

### CODE REVIEW

**Review by andrey-helldar — COMMENTED** [review]
Can you translate the rest of the keys?

- ID
- Signed in as
- Thanks,

If the "ID" value matches English and does not translate into Japanese, then you can add it to the exclusion file.

To do this, you need to create a `ja.php` file in the `excludes` folder.

https://github.com/Laravel-Lang/lang/tree/main/excludes

**Comment by wadakatu** [comment]
@andrey-helldar 

Okay.
I am working on it.

**Comment by wadakatu** [comment]
@andrey-helldar 

Thank you for waiting.

I dealt with the rest of translation except 'id'.
I added 'ID' key in the exclusion file.

**Review by andrey-helldar — APPROVED** [review]
ありがとうございます。

**Pull request merged**
