### PR TITLE
[nl]: Small translation fixes

### PR DESCRIPTION
**Pull request by chillbram**
- Trailing spaces where the original has one
- _mail_ -> _e-mail_, for consistency
- _het_ -> _dit_, for better sentence structure in its intended context

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
I think we can accept it

**Comment by andrey-helldar** [comment]
Dankjewel

**Comment by chillbram** [comment]
Cheers! @andrey-helldar if you need future help checking Dutch translations, you can ping me if required

**Comment by andrey-helldar** [comment]
@chillbram, do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by andrey-helldar** [comment]
> Yeah sure, add me to the team!

@caouecs, can you add him to the team?

**Comment by caouecs** [comment]
done

Welcome !!!

**Pull request merged**
