### PR TITLE
[th] Update json.json with official country name spellings

### PR DESCRIPTION
**Pull request by bact**
- Use country names and spellings in Thai according to Thailand Ministry of Foreign Affairs
- Fix those translations with `" name"` substring left
- Remove "ประเทศ" (country) and "เดือน" (month) prefixes of few translations, to make them consistent with other translations in the same category
- Fix word order ("qualifier number" -> "number qualifier") of few translations
- Remove "หรอครับ" particle at the end of few translations as they are repetitive (the beginning of these translation already made it clear that they are question)

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Hi!

Unfortunately, we don't have a native Thai speaker on our team to help with grammar.

The current translations you see are made by Google Translate.

**Review by andrey-helldar — APPROVED** [review]
ขอบคุณ

**Comment by andrey-helldar** [comment]
Do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by bact** [comment]
Thanks @andrey-helldar . You can assign the issues to me when there are translations related to Thai language or Thai community.

**Comment by andrey-helldar** [comment]
@caouecs, hi! Can you add @bact to our team?

**Comment by caouecs** [comment]
done ;)

**Comment by andrey-helldar** [comment]
@bact, welcome to the team!

**Comment by bact** [comment]
Thank you :)

**Pull request merged**
