### PR TITLE
[es] Translate 'Pagination Navigation'

### PR DESCRIPTION
**Pull request by luisprmat**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
I like the difference in languages:

EN: "Pagination Navigation"
ES: "Navegación por los enlaces de paginación"
RU: "Навигация"

😄

**Comment by caouecs** [comment]
Gracias

**Comment by luisprmat** [comment]
@andrey-helldar Spanish is not a language as cheap (low-cost, short in words) as English or others. So I couldn't find another way to describe this phrase in Spanish in this context without changing its meaning.

**Comment by andrey-helldar** [comment]
> @andrey-helldar Spanish is not a language as cheap (low-cost, short in words) as English or others. So I couldn't find another way to describe this phrase in Spanish in this context without changing its meaning.

I am not criticizing. On the contrary, I say that languages ​​are interesting. Somewhere you can describe it in one word, but somewhere the whole sentence is not enough. And that's great.

**Pull request merged**
