### PR TITLE
Solved: Parser deletes some existing tags for Laravel Jetstream

### PR DESCRIPTION
**Pull request by andrey-helldar**
Fix for #1848

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@caouecs, tests now give an error because in this PR I did not add keys to the localization files so as not to create noise.

After accepting the PR, the script will automatically do it.

**Review by luisprmat — APPROVED** [review]
It works! Thanks

This is after run `php app/keys`. The missing keys are generated successfully. 

image

I know this is done by Github actions automatically but I did it manually to test.
Very good!

**Comment by luisprmat** [comment]
Will this update be for a version 10.2? to avoid compatibility problems with some packages based in this one?

**Comment by luisprmat** [comment]
@andrey-helldar Now I wonder if it is possible to automatically recover the translations lost in these automatic commits:
- `{locale}.json` [249dad8](https://github.com/Laravel-Lang/lang/commit/249dad8026826a3f6ee16f2ac02168646330cef0#diff-685d141077f37ef51a522d5453d695c6d7d5f9e4b886493fc6337f971ca5cdea)
- Excludes [afb2189](https://github.com/Laravel-Lang/lang/commit/afb2189659f1e540412073a68a820f0ae293bbfe#diff-005969f0c812bc697c6d85fb6be0e859fe4c8d17bc728bff11cca88d026862e1)
Do we have to do it manually or have each contributor translate again?

**Comment by andrey-helldar** [comment]
Yes, I can do it.

**Comment by andrey-helldar** [comment]
@luisprmat, I returned the transfers

**Review by luisprmat — APPROVED** [review]

**Comment by caouecs** [comment]
I merge ?

**Comment by andrey-helldar** [comment]
@caouecs, yes. I added the key file and restored the translations.

**Comment by luisprmat** [comment]
@caouecs, yes, you can merge, i think that this issue has been fully and successfully resolved

**Comment by caouecs** [comment]
done, thank you

**Pull request merged**
