### PR TITLE
[id] Fixed missing translation

### PR DESCRIPTION
**Pull request by elzdave**
1. Fixed missed translation for 'accepted_if' in validation-inline.php
2. Fixed missed translation for 'accepted_if' in validation.php
3. Fixed missed 'The password is incorrect.' and 'Total:' in id.json

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you

**Comment by elzdave** [comment]
You're welcome :)

**Comment by elzdave** [comment]
Uhm, I think the 'Total:' should be marked as resolved too, because the 'Total:' in English has the same meaning in Bahasa Indonesia

**Comment by caouecs** [comment]
you can add it in exclude/id.php

**Pull request merged**
