### PR TITLE
Translate for PL

### PR DESCRIPTION
**Pull request by olsza**
ps. the word "Email" is spelled the same in Polish

ps2. Hope it's ok now, thanks @andrey-helldar

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]

**Comment by andrey-helldar** [comment]
@caouecs, allow to merge :)

**Comment by andrey-helldar** [comment]
PS: @olsza, the todo.md file is generated automatically when the `php script/todo.php` command is invoked:
https://github.com/Laravel-Lang/lang/blob/master/CONTRIBUTING.md#update-todo-file

**Comment by luisprmat** [comment]
Reviewing in the script `todo.php` to generate `todo.md` we watch that its compares `en.json` with each language searching strings non-translated.
If a string is in `en.json` but it isn't in the language is marked like `: not present`. But if it's as `en.json` as in the language`.json` it expects than translation is different to `en.json`, otherwise that string is added to *todo list* and the flag for this language never is green. 
Is there a way to fix this issue when the translation from English matches with translation for a specific language?

**Comment by andrey-helldar** [comment]
So far we have not looked for such a way, but I am thinking about it.

**Comment by caouecs** [comment]
Thank you

**Comment by caouecs** [comment]
for the fix, it's will be difficult, or we do a file with exceptions by language that todo.php reads before creating of todo.md

**Comment by andrey-helldar** [comment]
> for the fix, it's will be difficult, or we do a file with exceptions by language that todo.php reads before creating of todo.md

This is a separate topic for conversation. I'll think about it a bit longer and create a discussion.

**Pull request merged**
