### PR TITLE
revision keys Indonesia

### PR DESCRIPTION
**Pull request by mrrfly**
Jane Doe is a name. which means it's the same.

and Total in Indonesian means Total too.

Thanks :)

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@mrrfly, add this name to your exceptions file. This will allow you to display the translation statistics correctly: [excludes/id.php](https://github.com/Laravel-Lang/lang/blob/master/excludes/id.php)

**Comment by mrrfly** [comment]
@andrey-helldar ok i'll do it

**Comment by andrey-helldar** [comment]
@mrrfly, thank you, but are you sure that countries need to be excluded too?

Aren't the names in Indonesian the same as in English?

**Comment by mrrfly** [comment]
@andrey-helldar I'm sorry, it was my fault. I'll fix it right away.
I will commit again.

Much obliged! :)

**Review by andrey-helldar — APPROVED** [review]

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
