### PR TITLE
Translation of the default message of the validator

### PR DESCRIPTION
**Pull request by andrey-helldar**
Waiting for https://github.com/laravel/framework/pull/43837

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, hey!

New keys here :)

**Comment by Van4kk** [comment]
Got it, tomorrow will be done!

**Comment by andrey-helldar** [comment]
@Van4kk, translation keys are already available in our project 🙂

**Comment by dinhquochan** [comment]
Here for Vietnamese #2353 🙋‍♂️

**Comment by Van4kk** [comment]
Will be done today !

**Pull request merged**
