### PR TITLE
refactor: Update locales/bn/bn.json

### PR DESCRIPTION
**Pull request by arman-arif**
Bengali language translation update
Some untranslated English words and sentences have been translated

### CODE REVIEW

**Comment by andrey-helldar** [comment]
ধন্যবাদ

**Comment by andrey-helldar** [comment]
Do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by arman-arif** [comment]
Thank you so much for asking me. I will be really glad if I can help with such an open-source project.

I'm in. Looking forward to

**Comment by andrey-helldar** [comment]
@caouecs, will you do it? :)

**Comment by caouecs** [comment]
done

**Pull request merged**
