### PR TITLE
[hr] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@morpheus7CS can you help us and review this automatic pull request, please ? thanks by advance

**Comment by morpheus7CS** [comment]
Looks good, I would approve it. ❤️

**Comment by caouecs** [comment]
thank you

**Comment by caouecs** [comment]
The country names are same in English and in Croatian ? see https://github.com/Laravel-Lang/lang/blob/master/docs/statuses/hr.md

**Pull request merged**
