### PR TITLE
[source]: Improved translation of validation rules: `enum`, `exists`, `in` and `not_in`

### PR DESCRIPTION
**Pull request by andrey-helldar**
Today I ran into a problem when the text "The selected :attribute is invalid." does not reveal the reason of validator triggering at all.

Therefore, I suggest the following improvements for consideration:

| Key                 | Old Main Value                           | New Main Value                                                        |
|---------------------|-------------------------------------|------------------------------------------------------------------|
| `validation.enum`   | The selected :attribute is invalid. | The :attribute field value is not in the list of allowed values. |
| `validation.exists` | The selected :attribute is invalid. | The :attribute field value does not exist.                       |
| `validation.in`     | The selected :attribute is invalid. | The :attribute field value is not in the list of allowed values. |
| `validation.not_in` | The selected :attribute is invalid. | The :attribute field must not be in the list.                    |

| Key                 | Old Inline Value               | New Inline Value                                         |
|---------------------|--------------------------------|----------------------------------------------------------|
| `validation.enum`   | The selected value is invalid. | The selected value is not in the list of allowed values. |
| `validation.exists` | The selected value is invalid. | The selected value does not exist.                       |
| `validation.in`     | The selected value is invalid. | The selected value is not in the list of allowed values. |
| `validation.not_in` | The selected value is invalid. | The selected value must not be in the list.              |

@Laravel-Lang/laravel-lang, what do you think? Are we in?

### CODE REVIEW

**Comment by mohamedsabil83** [comment]
Yes, the new values make it more explicit like this.

**Comment by Oleksandr-Moik** [comment]
Yes, that's a great idea, I'm in! This version of the message is more descriptive of the problem. I am for the fact that we should change it in our translations.

And now I'm thinking - is it possible for us to offer these message changes in the framework itself? Maybe they will accept)

https://github.com/laravel/framework/blob/10.x/src/Illuminate/Translation/lang/en/validation.php

**Comment by andrey-helldar** [comment]
@Oleksandr-Moik, we can suggest, but whether Taylor will accept the changes is a question. But we won't know if we don't try)

I can send PR.

**Comment by andrey-helldar** [comment]
PR is published: https://github.com/laravel/framework/pull/50443

**Comment by mohamedsabil83** [comment]
Arabic ready #4308

**Comment by luisprmat** [comment]
Spanish ready: [#4309]

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, nope, there will be [no changes](https://github.com/laravel/framework/pull/50443#issuecomment-1988384833) to the core.

image

**Comment by luisprmat** [comment]
Right now they are busy with the release of Laravel 11, maybe later this PR can be reopened and it will be accepted.

**Comment by andrey-helldar** [comment]
Hardly. 7 hours ago PR was accepted into the 10th version branch.

https://github.com/laravel/framework/commits/10.x/

**Comment by andrey-helldar** [comment]
@luisprmat, here comes the proof that Taylor has at least two teams, one preparing today's Laravel 11 release and the other doing Laravel 10 support.

Laravel 10's minor update was released today on schedule. These updates are released every Tuesday.

https://github.com/laravel/framework/releases/tag/v10.48.0

**Pull request merged**
