### PR TITLE
[en, ru] Added missing translation key

### PR DESCRIPTION
**Pull request by andrey-helldar**
See https://github.com/laravel/jetstream/blob/1.x/stubs/livewire/resources/views/profile/delete-user-form.blade.php#L28

The todo file was not generated because this can create a conflict with other PRs.

### CODE REVIEW

**Comment by caouecs** [comment]
Your en.json is the reference ?

**Comment by andrey-helldar** [comment]
Sorry, I did not understand the essence of the question.

Today I was checking the accepted PRs in the Jetstream repository and saw one translation line that I missed. I added it in this PR to a file with English and translated it into Russian.

I left the link only as a source.

**Comment by caouecs** [comment]
Your en.json is up-to-date with Jetstream translation tags ?

**Comment by andrey-helldar** [comment]
Yes, and other keys from upstream 1.x, which should be published soon.

**Comment by andrey-helldar** [comment]
I did this:

1. Downloaded the entire repository;
2. Switched to the most recent commit that was committed to main [1.x](https://github.com/laravel/jetstream/compare/ac29502fd9184bb482e71e088879605f192cd16a...1.x) branch;
3. Found all translation strings for the query `__(`;
4. Added translation keys to the files.

At the moment, version [1.2.1](https://github.com/laravel/jetstream/compare/ac29502fd9184bb482e71e088879605f192cd16a...v1.2.1) contains all keys except this one. But PR with it has already been accepted and, therefore, it will soon be published.

**Comment by luisprmat** [comment]
The new key added for you to `en.json` (line 17) already has been added in my PR [#1341] (https://github.com/Laravel-Lang/lang/pull/1341). This is not merged yet. Besides there are two keys more in my PR missing in yours. This can cause conflicts in `en.json`

**Comment by luisprmat** [comment]
My reference is also the branch `1.x` of Laravel Jetstream with the last commits merged.

**Comment by luisprmat** [comment]
Speaking of referring new keys:
* ['If necessary, you may logout of all of your other ...'](https://github.com/laravel/jetstream/blob/1.x/stubs/livewire/resources/views/profile/logout-other-browser-sessions-form.blade.php#L12)
* ['Once your account is deleted, all of its resources and data ...'](https://github.com/laravel/jetstream/blob/1.x/stubs/livewire/resources/views/profile/delete-user-form.blade.php#L12)

This keys is not present neither in `en.json` nor in this PR, but they are in my PR (not merged)  (https://github.com/Laravel-Lang/lang/pull/1341)

**Comment by andrey-helldar** [comment]
> The new key added for you to `en.json` (line 17) already has been added in my PR [#1341] (#1341). This is not merged yet. Besides there are two keys more in my PR missing in yours. This can cause conflicts in `en.json`



> The new key added for you to `en.json` (line 17) already has been added in my PR [#1341] (#1341). This is not merged yet. Besides there are two keys more in my PR missing in yours. This can cause conflicts in `en.json`

I can check in a couple of hours and resolve the conflict.

**Comment by andrey-helldar** [comment]
@luisprmat, I checked. My PR is not creating conflict for #1341.

image

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
