### PR TITLE
Remove duplicate string

### PR DESCRIPTION
**Pull request by sajaddp**
Duplicate string removed.

### CODE REVIEW

**Comment by sajaddp** [comment]
@ariaieboy Why did it give an error?!

**Comment by ariaieboy** [comment]
> @ariaieboy Why did it give an error?!

you should not remove any translation key from the files every string exists for a reason

**Comment by sajaddp** [comment]
@ariaieboy This translation key is exactly duplicated!

**Comment by andrey-helldar** [comment]
@sajaddp, `Forgot Your Password?` !== `Forgot your password?`

**Comment by sajaddp** [comment]
@andrey-helldar 
You are right.
I'm sorry

**Pull request closed without merging**
