### PR TITLE
[de_CH]: Synced with [de]

### PR DESCRIPTION
**Pull request by kohlerdominik**

### CODE REVIEW

**Comment by kohlerdominik** [comment]
@andrey-helldar Is there any existing mechanic, so we could automatically sync [de_CH] from [de] for missing keys? de_CH is very similar to de, and fits out of the box easily.

There is one conversion that could be auto-applied:
- `ß` does not exist in de_CH, and should be replaced with `ss`. So search-replace `ß`→`ss`.

As soon as before-values in de and de_CH are not equal, they should no longer be auto-synced, obviously.

**Comment by andrey-helldar** [comment]
There are no mechanics for synchronizing these languages because, despite their similarities, they have completely different localization codes.

To replace `ß` with `ss`, you can use file-by-file text replacement in the IDE (Ctrl+H).

**Comment by andrey-helldar** [comment]
@sotten hey! Can you check another one?

**Comment by kohlerdominik** [comment]
> There are no mechanics for synchronizing these languages because, despite their similarities, they have completely different localization codes.
> 
> To replace `ß` with `ss`, you can use file-by-file text replacement in the IDE (Ctrl+H).

Hi
Yes, this is what I do right now. But it requires someone to do it manually; so if there would have been something similar in place, we could have automated it. But I agree that it's not worth to do it for one language, hence the question.

**Review by andrey-helldar — APPROVED** [review]
Danke!

**Pull request merged**
