### PR TITLE
[de] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@WhereIsLucas can you help us and review this automatic pull request, please ? thanks by advance

**Comment by kohlerdominik** [comment]
German and Swiss-German is very close, I'll review this, too.

**Comment by kohlerdominik** [comment]
Superseded by #1696

**Review by kohlerdominik — CHANGES_REQUESTED** [review]
Superseded by #1696

**Pull request closed without merging**
