### PR TITLE
[ES] Add new tags to en.json and add translation to Spanish for Laravel Jetstre…

### PR DESCRIPTION
**Pull request by luisprmat**
…am v1.2.1.

It's missing run script to update `todo.md`.

I didn't do to avoid conflicts with previous PR (it modifies this file too).

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@luisprmat, do you want to be in [referents](https://github.com/Laravel-Lang/lang/blob/master/referents.md) of the Spanish translation?

**Comment by luisprmat** [comment]
Yes, i'd like!

**Comment by andrey-helldar** [comment]
@caouecs, can you invite him to our team?

**Comment by caouecs** [comment]
> @caouecs, can you invite him to our team?

done

for review, I will try to do it this week-end ( big week at work )

**Review by luisprmat — COMMENTED** [review]
New translation tags used in password validation in Laravel Fortify v1.5.0, this package in turn is used in Jetstream.

This tags are in [https://github.com/laravel/fortify/blob/1.x/src/Rules/Password.php](https://github.com/laravel/fortify/blob/1.x/src/Rules/Password.php)

**Review by luisprmat — COMMENTED** [review]
Add tags used in Laravel fortify for validation:
* [The provided password does not match your current password.](https://github.com/laravel/fortify/blob/1.x/stubs/UpdateUserPassword.php#L27) - Update password
* [The provided password was incorrect.](https://github.com/laravel/fortify/blob/1.x/src/Http/Responses/FailedPasswordConfirmationResponse.php#L19) - Password Confirmation
* [The provided two factor authentication code was invalid.](https://github.com/laravel/fortify/blob/1.x/src/Http/Responses/FailedTwoFactorLoginResponse.php#L18) - Two Factor code validator

**Comment by caouecs** [comment]
Gracias

**Pull request merged**
