### PR TITLE
update fr.json

### PR DESCRIPTION
**Pull request by phikhi**
adding (lowercase) "yearly" missing field

### CODE REVIEW

**Comment by caouecs** [comment]
ok for me, if the new key exists

**Review by caouecs — APPROVED** [review]

**Comment by andrey-helldar** [comment]
@caouecs, I requested a translation file from the Laravel team, but they don't always respond quickly.

**Comment by andrey-helldar** [comment]
@phikhi, can you send the translation file from spark?

**Comment by phikhi** [comment]
@andrey-helldar Hi,

Problem is that the key I added is not available in the spark lang file right now.
The "yearly" key is used on the billing portal, but not translatable yet. 

Do you prefer waiting that is officially available ?

**Comment by andrey-helldar** [comment]
Yes, we prefer matching official keys Best Regards    Andrey Helldar17:36, 11 марта 2022 г., phikhi ***@***.***>:
@andrey-helldar Hi,
Problem is that the key I added is not available in the spark lang file right now.
The "yearly" key is used on the billing portal, but not translatable yet.
Do you prefer waiting that is officially available ?

**Comment by phikhi** [comment]
@andrey-helldar Ok no problem, I understand.

Feel free to close the pull request then ;)
Thank you for your time

**Pull request closed without merging**
