### PR TITLE
[de] some german translations

### PR DESCRIPTION
**Pull request by sotten**
some german translations
Update locales/de/de.json

### CODE REVIEW

**Comment by caouecs** [comment]
danke

**Comment by andrey-helldar** [comment]
@sotten, dankeschön!

Can I ask you to translate the [missing keys](https://laravel-lang.github.io/lang/statuses/de.html)?

**Comment by ottenso** [comment]
I have already translated the first 50% of the missing keys ​​in this pull request.  I'll tackle the missing keys ​​soon.

**Comment by andrey-helldar** [comment]
> I have already translated the first 50% of the missing keys ​​in this pull request. I'll tackle the missing keys ​​soon.

Thank you! :)

**Pull request merged**
