### PR TITLE
[sw]: Translation of Inline-json and excludes

### PR DESCRIPTION
**Pull request by Pheogrammer**
I have translated the added keywords to Swahili

### CODE REVIEW

**Review by andrey-helldar — CHANGES_REQUESTED** [review]
Inline translations must not contain a reference to a variable.

For example,

Main file:

```json
"The :attribute must be a valid role.": "This field must be a valid role.",
"The given :attribute has appeared in a data leak. Please choose a different :attribute.": "The given :attribute has appeared in a data leak. Please choose a different :attribute."
```

Inline file:

```json
"The :attribute must be a valid role.": "This field must be a valid role.",
"The given :attribute has appeared in a data leak. Please choose a different :attribute.": "The given field has appeared in a data leak. Please choose a different field."
```

**Comment by andrey-helldar** [comment]
Perhaps the filenames are misleading.

| Filename           | Description                                 |
|--------------------|---------------------------------------------|
| `json.json`        | file with json translation keys.            |
| `json-inline.json` | file with inline translations of json keys. |
| `php.json`         | file with php translation keys.             |
| `php-inline.json`  | file with inline translations of php keys.  |

**Comment by andrey-helldar** [comment]
For example:

```json
"accepted": "Uwanja huu ni lazima kukubaliwa.",
"accepted_if": "Uwanja huu ni lazima kukubaliwa wakati :other ni :value.",
```

**Comment by Pheogrammer** [comment]
Oh now i get it

**Comment by andrey-helldar** [comment]
@Pheogrammer, hi! Can you resolve inline messages?

**Pull request closed without merging**
