### PR TITLE
[bn]: Translation Update

### PR DESCRIPTION
**Pull request by arman-arif**

### CODE REVIEW

**Review by arman-arif — COMMENTED** [review]
> "mo": "mo",
@andrey-helldar can you please tell me what does "mo" mean hear?

**Comment by andrey-helldar** [comment]
> > "mo": "mo",
> 
> @andrey-helldar can you please tell me what does `"mo"` mean hear?

This is shortened from the "month" word:

```
yr - year
mo - month
```

**Review by andrey-helldar — APPROVED** [review]
আপনাকে ধন্যবাদ

**Comment by arman-arif** [comment]
> > > "mo": "mo",
> > 
> > 
> > @andrey-helldar can you please tell me what does `"mo"` mean hear?
> 
> This is shortened from the "month" word:
> 
> ```
> yr - year
> mo - month
> ```

Got it thank you

**Comment by andrey-helldar** [comment]
You're welcome!

**Pull request merged**
