### PR TITLE
Optimizing the location of documentation files

### PR DESCRIPTION
**Pull request by andrey-helldar**
1. Created the directory `docs`;
2. Since the file `TODO.md` reflected the completion status, renamed it to `status.md` and put it in the folder `docs`;
3. All files of statuses by language are generated in the folder `docs/statuses`;
4. Cleaned up the [README.md](https://github.com/andrey-helldar/Laravel-lang/tree/patch/github-pages#readme) file by adding a link to the file `docs/index.md`;
5. Split the file `docs/index.md` into pages.
6. Made the documentation available in both the [repository](https://github.com/andrey-helldar/Laravel-lang/blob/patch/github-pages/docs/index.md) and [GitHub Pages](https://andrey-helldar.github.io/Laravel-lang/) - this is a test link. The main one will be here: [https://laravel-lang.github.io/lang](https://laravel-lang.github.io/lang).
7. I renamed the `contributing.md` file to `contributing-to-dev.md` because the GitHub Pages compiler considers this word to be a reserved word and does not allow creating a page with such a link.

image

image

image

image

image

**PS:** The block at the bottom of the page is generated by GitHub Pages itself. When generated in the Laravel-lang project, all links will point to Laravel-lang, and the maintainer will be @caouecs.

image

**PS2:** I reduced the number of columns from 12 to 8 because this is the maximum number at which GitHub Pages correctly renders the table.

**PS3:** The "Documentation" link from the [README.md](https://github.com/andrey-helldar/Laravel-lang/tree/patch/github-pages) page leads to the md file (if necessary, I can replace it with GitHub Pages).

> image

**PS4:** Link to GitHub Pages is available from the "environment" block of the repository page:

> image
>
> image

After accepting the PR, don't forget to set up the branch to generate:

> image

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, what do you think? 😊

**Comment by caouecs** [comment]
I'm ok

**Comment by caouecs** [comment]
You have some conflicts:

 * CHANGELOG.md
 * app/main/Processors/Todo/Processor.php
 * todo/af.md
 * todo/fr.md

**Comment by andrey-helldar** [comment]
Yes, I'm just solving the conflict :)

**Comment by andrey-helldar** [comment]
Ready

**Comment by caouecs** [comment]
go go go

**Comment by caouecs** [comment]
Why the title is "Laravel-lang by caouecs" ? No needed "by caouecs"

**Comment by andrey-helldar** [comment]
> Why the title is "Laravel-lang by caouecs" ? No needed "by caouecs"

GitHub Pages automatically generates. I do not know why it is so.
I set the title, but it is not for this: https://github.com/Laravel-Lang/lang/blob/master/docs/_config.yml

**Comment by andrey-helldar** [comment]
Can you set up GitHub Pages for the "master" branch?

image

image

**Comment by caouecs** [comment]
done

**Comment by andrey-helldar** [comment]
Hmm... Something wrong...

https://laravel-lang.github.io/lang/ > click "documentation" and see https://laravel-lang.github.io/lang/docs/index.md - GitHub Pages was unable to render pages...

1. This file must be removed: https://github.com/Laravel-Lang/lang/blob/master/_config.yml - The configuration is already in the docs folder: https://github.com/Laravel-Lang/lang/tree/master/docs
2. In the settings you need to specify the root folder `docs` (not `/`).

**Comment by caouecs** [comment]
done

**Comment by andrey-helldar** [comment]
Nice :)

https://laravel-lang.github.io/lang/

image

**Comment by andrey-helldar** [comment]
> Why the title is "Laravel-lang by caouecs" ? No needed "by caouecs"

I understood why there was such an inscription. A long time ago, you activated GitHub Pages when the repository was in your profile. He generated and saved.

**Comment by caouecs** [comment]
Yes, I do the same conclusion

**Comment by mohamedsabil83** [comment]
Great work @andrey-helldar 👍🏽

**Comment by andrey-helldar** [comment]
@mohamedsabil83, thank you! 😊

@caouecs, I thought, maybe we can replace the documentation link from markdown to Pages? What do you think?

Screenshot_2021-04-02-20-34-28-530_com android chrome

**Comment by caouecs** [comment]
ok

**Comment by andrey-helldar** [comment]
I'll also think about how to beautifully change the pages of missing keys.

Now the output is a key-value pair separated by a colon. Personally, I am confused and I think that this whole line is the key.

I'll think about how to make it beautiful.

image

**Pull request merged**
