### PR TITLE
[es] Translate new Fortify key

### PR DESCRIPTION
**Pull request by luisprmat**

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
Gracias

**Comment by luisprmat** [comment]
Sorry! This time i forgot put the preffix `[es]` to the PR.

**Comment by andrey-helldar** [comment]
Don't worry, don't forget :)

I'm adding a colon after the prefix because I'm too lazy to manually write a changelog when creating a release 😅

I just press the "Generate release notes" button and GitHub itself makes a list of accepted PRs after the last release))

image

Previously, this list was manually formed and it looked like:

```
### Changes
* [ar]: #2326 Translate new phrase of Fortify
* [es]: #2327 Translate new Fortify key
```

Just simplifying the process of creating a release while maintaining a beautiful look of the changelog :)

PS: On the site, it does not look very nice now due to the peculiarities of GitHub - you need to somehow handle the links. I recently started writing a Vite plugin to do this, but it's not ready for public release yet.

image

**Comment by luisprmat** [comment]
@andrey-helldar There are new [validation](https://github.com/laravel/laravel/pull/5975) keys. Please run scripts to generate keys!

**Comment by andrey-helldar** [comment]
@luisprmat, ok.

In general, our script runs auto-update once a day at 00:00 UTC.

**Comment by luisprmat** [comment]
Does't this script generate the php-inline keys? How to do to generate this keys?

**Pull request merged**
