### PR TITLE
🌐 [AR] Translate new phrases

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@Khuthaily, can you see the translation? Suddenly you notice something.

**Comment by andrey-helldar** [comment]
@mohamedsabil83, can you update the todo.md file?

**Comment by mohamedsabil83** [comment]
> @mohamedsabil83, can you update the todo.md file?

Work on it

**Comment by mohamedsabil83** [comment]
@andrey-helldar it's ready

**Comment by andrey-helldar** [comment]
@caouecs, I think this PR can be accepted. If @mohamedsabil83 or @Khuthaily notice mistakes, they will send a PR.

**Comment by caouecs** [comment]
thank you

**Comment by mohamedsabil83** [comment]
> thank you

Y.W.

**Comment by andrey-helldar** [comment]
> > thank you
> 
> Y.W.

`You are welcome`
`You're welcome`
`U're welcome`
`Y.W.`
`YW`
`yw`
`w`
` `

PS: Sorry, I could not resist developing the idea of word reduction. Good mood 🍻

**Pull request merged**
