### PR TITLE
[lt] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@Marius-K can you help us and review this automatic pull request, please ? thanks by advance

**Comment by Marius-K** [comment]
Hello @caouecs, I quickly went through pull request and saw some mistakes, but overall it's decent! I will fix the mistakes in new PR later, is that okay?

**Comment by caouecs** [comment]
Ok, I merge this pull request, and we wait your updates

**Comment by caouecs** [comment]
thank you everybody

**Pull request merged**
