### PR TITLE
[az] Add missing translations and fix incorrect ones

### PR DESCRIPTION
**Pull request by Maharramoff**

### CODE REVIEW

**Comment by Maharramoff** [comment]
> In cases where `:attribute` appears at the beginning of a sentence, replace with `:Attribute`

✔ @andrey-helldar

**Comment by Maharramoff** [comment]
> Also, can you update [other files](https://github.com/Laravel-Lang/lang/tree/main/locales/az) too?

Sure

**Review by andrey-helldar — APPROVED** [review]

**Comment by andrey-helldar** [comment]
@Maharramoff, do you plan to add a file update to this PR or a new one?

**Comment by Maharramoff** [comment]
> @Maharramoff, do you plan to add a file update to this PR or a new one?

After a while :)

**Comment by andrey-helldar** [comment]
Thank you

**Pull request merged**
