### PR TITLE
[uz_Cyrl] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@makhsam can you help us and review this automatic pull request, please ? thanks by advance

**Comment by makhsam** [comment]
Hello @caouecs! OK, I will review them. I need some time.

**Comment by makhsam** [comment]
There are some missing keys that need to be translated

**Comment by andrey-helldar** [comment]
> There are some missing keys that need to be translated

The script that was responsible for the translation did not run on nested arrays, for example, "between" in the "validation.php" file. Because of this, not all keys have been translated.

**Comment by makhsam** [comment]
Hello @andrey-helldar OK

**Comment by caouecs** [comment]
@makhsam I merge and you do a pull request after with updates ?

**Comment by caouecs** [comment]
I merge, and you will be able to fix after

**Pull request merged**
