### PR TITLE
[ja]: Fix translation

### PR DESCRIPTION
**Pull request by sshd911**
I think this word is not user friendly.

### CODE REVIEW

**Review by wadakatu — COMMENTED** [review]
"正規表現" is not definitely user-friendly. I couldn't agree more about it.
Therefore, "形式" looks good for me.

However, I think that "正しい形式" is better expression than "有効な形式".
What do you think about it?

**Comment by wadakatu** [comment]
@sshd911

**Comment by sshd911** [comment]
@wadakatu 

Thank you for your review !
I'm glad you agree with me.
And I also agree about "正しい形式".

**Comment by sshd911** [comment]
I recommitted, please confirm !
https://github.com/Laravel-Lang/lang/pull/2315/commits/712502e227f22659829593fe6765bcadfd81acd8

**Review by wadakatu — APPROVED** [review]
Looks Good To Me.

**Comment by sshd911** [comment]
Thanks!

**Review by andrey-helldar — APPROVED** [review]
Thank you

**Pull request merged**
