### PR TITLE
[en, ru] Added translation of new phrases in Jetstream

### PR DESCRIPTION
**Pull request by andrey-helldar**
PR: https://github.com/laravel/jetstream/pull/300

Original file: https://github.com/laravel/jetstream/blob/1.x/stubs/app/Providers/JetstreamWithTeamsServiceProvider.php

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@Laravel-Lang/laravel-lang, guys, I think this PR will be accepted, so I added new keys for Jetstream.

**Comment by luisprmat** [comment]
I think we are going ahead, let's wait what Taylor thinks although I think it's good that this PR is merged

**Comment by andrey-helldar** [comment]
Merged.

image

**Comment by andrey-helldar** [comment]
> I think we are going ahead, let's wait what Taylor thinks although I think it's good that this PR is merged

I agree that it is not worth adding the translation to unaccepted PRs. But in this I personally was sure that they would accept it, since it does not break backward compatibility and implements the translation of phrases.

**Comment by caouecs** [comment]
Thank you

**Pull request merged**
