### PR TITLE
[uz_Cyrillic] [uz_Latin] Improved passwords && validation messages in Uzbek

### PR DESCRIPTION
**Pull request by makhsam**

### CODE REVIEW

**Comment by caouecs** [comment]
Thank you but we need someone to check your translations

**Comment by andrey-helldar** [comment]
I need some time. Thank you for your patience.

**Comment by makhsam** [comment]
> Thank you but we need someone to check your translations

I am from Uzbekistan. I liked this package a lot and have used in my project. But I found that there is a lot of syntax and grammar errors in translation files. I fixed them all. It would be more effective if someone who knows Uzbek checks this pull request. Thanks!

**Review by andrey-helldar — APPROVED** [review]
@caouecs, I checked, everything is fine.
Translation keys in place.
In some places, the text is translated too accurately, but this is very difficult in the realities of the Uzbek language. It can be seen that @makhsam was very carried away in a good way.
This is great PR.

**Comment by caouecs** [comment]
Thank you

**Comment by andrey-helldar** [comment]
@makhsam, can you translate other keys for the [uz_Cyrillic](https://github.com/Laravel-Lang/lang/blob/master/todo.md#uz_Cyrillic) and [uz_Latin](https://github.com/Laravel-Lang/lang/blob/master/todo.md#uz_Latin)?

**Comment by makhsam** [comment]
@andrey-helldar Thanks for comments, ok I'll try to do them later.

**Comment by andrey-helldar** [comment]
@makhsam, if you want you can be [referent](https://github.com/Laravel-Lang/lang/blob/master/referents.md) for the Uzbek translation.

**Comment by makhsam** [comment]
@andrey-helldar Thanks but what referents actually do?

**Comment by andrey-helldar** [comment]
> @andrey-helldar Thanks but what referents actually do?

They keep track of the translation into the languages ​​for which they are responsible.

If there are untranslated phrases, they are translated.
If someone has sent a PR in their language, then they check the correctness of the translation.

**Pull request merged**
