### PR TITLE
[zh_CN] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@overtrue can you help us and review this automatic pull request, please ? thanks by advance

**Comment by overtrue** [comment]
I think it's great, it would be perfect if there were spaces between variables and Chinese characters, for example: 

```diff
- :other为:value时禁止此字段。
+ :other 为 :value 时禁止此字段。
```

**Comment by caouecs** [comment]
I merge and I do it

**Comment by caouecs** [comment]
done

**Comment by caouecs** [comment]
@overtrue We have a problem with two not translated tags : Qatar and ID

Can you help us ? for zh_CN, zh_HK and zh_TW

thanks by advance

**Comment by overtrue** [comment]
ID No translation required, and Qatar Looks like a place name?

**Comment by overtrue** [comment]
@caouecs There has a list of the country names in Chinese. https://www.nationsonline.org/oneworld/countrynames_chinese.htm

**Comment by overtrue** [comment]
It is recommended that country names are translated by calling the Language Translation API directly

**Comment by overtrue** [comment]
@andrey-helldar FYI.

**Comment by caouecs** [comment]
done for "ID"

**Comment by overtrue** [comment]
> for Qatar, it's same translation for three languages ?

Actually it is not the same, for example, zh_CN -> 卡塔尔, zh_HK/zh_TW -> 卡塔爾

However, there is no complete list of the differences between the three languages, so it is best to just do the API to the specific language translation level and then leave it to everyone to contribute to fix it.

I will try to find the corresponding reference translations to improve them.

**Comment by caouecs** [comment]
Ok, I update Qatar

**Pull request merged**
