### PR TITLE
[ja]: Add translation

### PR DESCRIPTION
**Pull request by wadakatu**
added some Japanese translation.

Hope it helps.

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]

**Comment by andrey-helldar** [comment]
ありがとうございます。

**Comment by andrey-helldar** [comment]
Do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by wadakatu** [comment]
@andrey-helldar 

Thank you for your offer.
I am very interested to join your team :)

I will do my best to maintain Japanese translation 🤝

**Comment by andrey-helldar** [comment]
@caouecs, can you add a new member in our team?

**Comment by caouecs** [comment]
Welcome !

**Pull request merged**
