### PR TITLE
[IT] Translated missing items in it.json

### PR DESCRIPTION
**Pull request by sniperwolf**
[IT] Translated missing items in it.json

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@sniperwolf, can you translate the [missing keys](https://github.com/Laravel-Lang/lang/blob/master/todo.md#it)?

**Comment by caouecs** [comment]
> @sniperwolf, can you translate the [missing keys](https://github.com/Laravel-Lang/lang/blob/master/todo.md#it)?

the best should be to add all missing tags...

**Comment by caouecs** [comment]
Grazie for translations ;)

**Comment by sniperwolf** [comment]
I will translate them ASAP 👍

**Pull request merged**
