### PR TITLE
Updated ro.json

### PR DESCRIPTION
**Pull request by Van4kk**
- Added week days
- Moldova corrected

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Do you use days-of-week keys in your application or in Laravel packages?

**Comment by Van4kk** [comment]
> Do you use days-of-week keys in your application or in Laravel packages?

Yes, thats the reason why I added it

**Comment by andrey-helldar** [comment]
> > Do you use days-of-week keys in your application or in Laravel packages?
> 
> Yes, thats the reason why I added it

Your app OR laravel packages?

**Comment by Van4kk** [comment]
> > > Do you use days-of-week keys in your application or in Laravel packages?
> > 
> > 
> > Yes, thats the reason why I added it
> 
> Your app OR laravel packages?

web app for and Romanian transport company

**Comment by andrey-helldar** [comment]
Understood. Our project only contains keys for Laravel projects.

You can easily create your own project by placing the translation keys necessary for your application in it. You can use the [`Laravel-Lang/translations-template`](https://github.com/Laravel-Lang/translations-template) template for this.

Our [`publisher`](https://publisher.laravel-lang.com/installation/) will automatically see your project and apply all the necessary changes. Of course, if you use our [`publisher`](https://publisher.laravel-lang.com/installation/).

**Comment by Van4kk** [comment]
> Understood. Our project only contains keys for Laravel projects.
> 
> You can easily create your own project by placing the translation keys necessary for your application in it. You can use the [`Laravel-Lang/translations-template`](https://github.com/Laravel-Lang/translations-template) template for this.
> 
> Our [`publisher`](https://publisher.laravel-lang.com/installation/) will automatically see your project and apply all the necessary changes. Of course, if you use our [`publisher`](https://publisher.laravel-lang.com/installation/).

OK, thank you !

**Pull request closed without merging**
