### PR TITLE
[pl] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@olsza can you help us and review this automatic pull request, please ? thanks by advance

**Comment by marcinlawnik** [comment]
Hi,

I am a native Polish speaker and this looks good to me.

**Comment by caouecs** [comment]
thank you

I merge, but it's possible after to check

**Comment by caouecs** [comment]
In Polish, the names of countries are same than in English ?

**Comment by marcinlawnik** [comment]
> 
> 
> In Polish, the names of countries are same than in English ?

No, in general no, why are you asking?

**Comment by marcinlawnik** [comment]
Now after looking again I see that there are a few strings I would change for better "feel". I'll do a PR later.

**Comment by marcinlawnik** [comment]
BTW thanks for all the great work here ;)

**Pull request merged**
