### PR TITLE
Adding a percentage of translations

### PR DESCRIPTION
**Pull request by andrey-helldar**
**Before:**

image

**After:**

image

PS: I just wanted to do 😊

### CODE REVIEW

**Comment by luisprmat** [comment]
Idea! How about a percentage for each language?

**Comment by andrey-helldar** [comment]
> Idea! How about a percentage for each language?

This is possible, but on the page of each language - you should not add to the table, otherwise there will be too much text.

But on the pages of localizations, I personally think this information will be redundant, since the number of untranslated elements is already displayed there.

Correct if I'm wrong.

**Comment by caouecs** [comment]
I think it's not interesting because it's just on completed language, not on the number of tags in all languages

**Comment by andrey-helldar** [comment]
@caouecs, are you talking about my proposal or @luisprmat's idea?

**Comment by caouecs** [comment]
> @caouecs, are you talking about my proposal or @luisprmat's idea?

your idea, the global percentage :)

**Comment by andrey-helldar** [comment]
> > @caouecs, are you talking about my proposal or @luisprmat's idea?
> 
> your idea, the global percentage :)

I understood. Now it also seems to me that it is better to calculate by the number of keys, rather than localizations.

I'll add the code shortly.

**Comment by andrey-helldar** [comment]
@caouecs, I updated the code and screenshot in the first post :)

**Comment by caouecs** [comment]
33% is better

**Comment by andrey-helldar** [comment]
> 33% is better

Remove the number of lines and leave only percentages?

**Comment by caouecs** [comment]
No, I said, 33% is better to see than 3% from your first commit ;)

**Comment by caouecs** [comment]
thank you

**Comment by andrey-helldar** [comment]
> No, I said, 33% is better to see than 3% from your first commit ;)

😅

**Pull request merged**
