### PR TITLE
[zh_CN]: Translate new phrases

### PR DESCRIPTION
**Pull request by SuperPx-CN**
Translate new phrases

### CODE REVIEW

**Comment by andrey-helldar** [comment]
@SuperPx-CN, it is not necessary to close one PR and create a new one. You can push commits to an existing branch and the changes will automatically get into the PR created from it.

**Review by andrey-helldar — APPROVED** [review]
It's ok for me

**Comment by SuperPx-CN** [comment]
> 对我来说还好

Thank

**Comment by overtrue** [comment]
@SuperPx-CN `locales/zh_CN/json-inline.json` 剩余部分也一起翻译了呗

**Comment by SuperPx-CN** [comment]
> @SuperPx-CN `locales/zh_CN/json-inline.json` 剩余部分也一起翻译了呗

可以的

**Review by overtrue — APPROVED** [review]

**Comment by overtrue** [comment]
感谢🙏

**Review by andrey-helldar — APPROVED** [review]
谢谢

**Pull request merged**
