### PR TITLE
fix fa translation

### PR DESCRIPTION
**Pull request by ariaieboy**

### CODE REVIEW

**Comment by ariaieboy** [comment]
> I probably took the PR too quickly. Sorry :)
> 
> PS: You don't need to change `:Attribute` to `:attribute`. Laravel has a feature out of the box where `:Attribute` capitalizes the first letter after a replacement. Since the sentence begins with a capital letter, it is correct to do so. In the case of localization fa, this does not play any role.

in my repo the PHPUnit test failed because of that "A" that's why I've changed it.

**Comment by andrey-helldar** [comment]
Hmm... I'll check it out :)

**Comment by andrey-helldar** [comment]
Can I accept PR or will you still work?

**Comment by ariaieboy** [comment]
> Can I accept PR or will you still work?

I think it's all good.

about the test that was my fault I didn't read the error message correctly that was because of using :atteribute in inline json. :)

**Comment by andrey-helldar** [comment]
Yes, I'm confused too)

**Pull request merged**
