### PR TITLE
[sr, uz, me] Rename *_Cyrillic to *_Cyrl and *_Latin to *_Latn (php Intl)

### PR DESCRIPTION
**Pull request by andrey-helldar**
Based on https://github.com/Laravel-Lang/lang/issues/1269#issuecomment-733190706

### CODE REVIEW

**Comment by caouecs** [comment]
I'm ok but it's a big change ( new version needed )

**Review by LukaLatkovic — CHANGES_REQUESTED** [review]
As i said in #1269 [comment](https://github.com/Laravel-Lang/lang/issues/1269#issuecomment-734295840)

As for uz folders, according to [this](https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=uz_Cyrl_UZ) and [this](https://icu4c-demos.unicode.org/icu-bin/locexp?d_=en&_=uz_Latn_UZ) they should be renamed to uz_Cyrl_UZ and uz_Latn_UZ

**Review by LukaLatkovic — APPROVED** [review]
All good now

**Comment by andrey-helldar** [comment]
@caouecs, ping

**Comment by caouecs** [comment]
version 8 ? :)

**Comment by andrey-helldar** [comment]
I think yes) Change is necessary and big.

**Comment by caouecs** [comment]
I prepare v8

**Comment by andrey-helldar** [comment]
Merci! J'ai publié ma version.

**Pull request merged**
