### PR TITLE
[vi] Spelling mistake

### PR DESCRIPTION
**Pull request by xcaro**
There are some spelling mistakes for the Vietnamese.

### CODE REVIEW

**Comment by caouecs** [comment]
Hello,
I'm not specialist in Vietnamese language, but what is the difference in your changes ?

**Comment by xcaro** [comment]
Hi @caouecs ,

There is a 1984 regulation that advocate for using "i" if the word is mono-syllabic and not freely-standing. And the usage of "y" and "i" is a mess in this translation.

Thanks,

**Comment by caouecs** [comment]
Thank you

**Comment by dinhquochan** [comment]
> Hi @caouecs ,
> 
> 
> 
> There is a 1984 regulation that advocate for using "i" if the word is mono-syllabic and not freely-standing. And the usage of "y" and "i" is a mess in this translation.
> 
> 
> 
> Thanks,

:) Thiệt sự là không hề biết có qui định này. Cảm ơn bạn rất nhiều 🎉

**Pull request merged**
