### PR TITLE
[IT] Added missing translations

### PR DESCRIPTION
**Pull request by michaelcozzolino**
It's my first PR, hope it's fine :)

### CODE REVIEW

**Comment by andrey-helldar** [comment]
Codestyle is ok. I checked. Ignore the test.

**Comment by andrey-helldar** [comment]
Grazie

**Comment by masterix21** [comment]
Grazie @michaelcozzolino, correggerò giusto due cosette per un errore di forma con un PR.

@andrey-helldar, there are errors in the translation: next time, feel free to contact me for a check. I'll release a PR in the next minutes to fix it.

**Comment by andrey-helldar** [comment]
@michaelcozzolino, https://github.com/Laravel-Lang/lang/pull/2051/files

**Pull request merged**
