### PR TITLE
[hy] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@arm092 can you help us and review this automatic pull request, please ? thanks by advance

**Review by arm092 — COMMENTED** [review]
The first part of the review

**Comment by caouecs** [comment]
I merge and I update

**Comment by caouecs** [comment]
Thank you @arm092 for this first review

can you do a pull request with the rest of review ? thanks by advance

**Pull request merged**
