### PR TITLE
[en, es] Update wording translation

### PR DESCRIPTION
**Pull request by luisprmat**
Taylor has updated this translation
[profile/logout-other-browser-sessions-form.blade.php](https://github.com/laravel/jetstream/commit/055be8529b4fb45897e9d5ef42eee0b2a45c8bde)

### CODE REVIEW

**Comment by caouecs** [comment]
We consider this tag as an updated tag or a new tag ?

**Comment by luisprmat** [comment]
I think we should modify it because if a user already has an existing project and updates jetstream their translations will not be affected if he does not overwrite the views. Also if someone installs jetstream they usually do it on a new project. So I don't think these two tags should coexist

**Comment by caouecs** [comment]
Ok, I merge your pull request and after I update all language with this tag

**Comment by caouecs** [comment]
Gracias

**Pull request merged**
