### PR TITLE
[th]: Update translation

### PR DESCRIPTION
**Pull request by pichaya07**

### CODE REVIEW

**Review by andrey-helldar — APPROVED** [review]
ขอบคุณ

**Comment by andrey-helldar** [comment]
Do you want to join our team?

Each of us is engaged in the fact that he monitors the chosen localization. When you need to fix something or new keys have been added - translate them. When someone creates a PR for this localization, check it out.

Usually when someone submits a localization PR, @caouecs or I assign it to the users to check against the [referent](https://laravel-lang.com/referents.html) table.

Interesting?

**Comment by pichaya07** [comment]
@andrey-helldar sure, i'd love to join the team

**Comment by andrey-helldar** [comment]
> @andrey-helldar sure, i'd love to join the team

@caouecs, can you add @pichaya07 to the team?

**Comment by caouecs** [comment]
Bienvenue ! Welcome !

**Pull request merged**
