### PR TITLE
[mk] Machine translation of missing keys

### PR DESCRIPTION
**Pull request by andrey-helldar**

### CODE REVIEW

**Comment by caouecs** [comment]
@keljtanoski can you help us and review this automatic pull request, please ? thanks by advance

**Comment by keljtanoski** [comment]
> @keljtanoski can you help us and review this automatic pull request, please ? thanks by advance

Sure, no problem, will do in the upcoming couple of days.

**Comment by caouecs** [comment]
@keljtanoski  I merge this pull request, and after you will be able to do your own pull request directly here ;)

**Comment by keljtanoski** [comment]
> @keljtanoski I merge this pull request, and after you will be able to do your own pull request directly here ;)

Gotcha, thank you, by doing a quick scan i noticed that some of the words were not quite accurately translated, but i will make some updates and update the MK lang file.

Thank you for the awesome work you've done so far.

**Pull request merged**
